file(GLOB_RECURSE COMMON_SOURCES "common/*.cc")
add_library(runtime_common SHARED ${COMMON_SOURCES})
find_path(BRPC_INCLUDE_PATH NAMES brpc/server.h)
find_library(BRPC_LIB NAMES brpc)
if((NOT BRPC_INCLUDE_PATH) OR (NOT BRPC_LIB))
        message(FATAL_ERROR "Fail to find brpc")
endif()
find_package(OpenSSL REQUIRED)
find_path(LEVELDB_INCLUDE_PATH NAMES leveldb/db.h)
find_library(LEVELDB_LIB NAMES leveldb)
if ((NOT LEVELDB_INCLUDE_PATH) OR (NOT LEVELDB_LIB))
        message(FATAL_ERROR "Fail to find leveldb")
endif()
include_directories(${LEVELDB_INCLUDE_PATH})
        
target_link_libraries(runtime_common ${BRPC_LIB} flex_rt_mutable_graph flex_plan_proto)
install_flex_target(runtime_common)

file(GLOB_RECURSE EXECUTE_SOURCES "execute/*.cc" "utils/*.cc")
add_library(runtime_execute SHARED ${EXECUTE_SOURCES})
target_link_libraries(runtime_execute runtime_common)
install_flex_target(runtime_execute)
